#!/usr/bin/env python
import paramiko
import sys

def check_ssh(host, user, passwd):
    client = paramiko.SSHClient()
    client.set_missing_host_key_policy(paramiko.AutoAddPolicy())

    try:
        client.connect(host, username=user, password=passwd, timeout=10)
    except paramiko.AuthenticationException:
        return "NOK"
    except paramiko.SSHException as sshException:
        return "NOK"
    except Exception as e:
        return "NOK"
    finally:
        client.close()

    return "OK"

if __name__ == "__main__":
    if len(sys.argv) != 4:
        print("Usage: python ssh_check.py <hostname> <username> <password>")
        sys.exit(1)

    hostname = sys.argv[1]
    username = sys.argv[2]
    password = sys.argv[3]
    #you can use a loop and concurrent to test many devices.
    result = check_ssh(hostname, username, password)
    print(result)
